version: "3"
services:  
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    networks:
      - postgres-net
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    volumes:
      - ./storage-layer/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - postgres-net
    restart: unless-stopped


  ingestion-service:
    build: ./ingestion-layer
    restart: always
    environment:
      - KAFKA_URL=kafka:9092
    networks:
      - kafka-net
    depends_on:
      - kafka

  processing-service:
    image: jeffail/benthos
    restart: always
    ports:
      - 4195:4195
    volumes:
      - ./processing-layer/config.yaml:/benthos.yaml
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka-net
      - postgres-net
    depends_on:
      - storage-service

  storage-service:
    build: ./storage-layer
    restart: always
    ports:
      - 8000:8000
    environment:
      - POSTGRES_URL=postgres:5432
    networks:
      - postgres-net
    depends_on:
      - postgres
  
networks:
  kafka-net:
    driver: bridge
  postgres-net:
    driver: bridge

volumes:
  postgres_data: