input:
  kafka:
    addresses:
    - ${KAFKA_BROKER:localhost:9094}
    topics:
    - ${KAFKA_TOPIC:users}
    consumer_group: ingestionlayer

pipeline:
  processors:
    - mapping: |
        root.username = this.username
        root.payment_method = this.subscription.payment_method
        root.plan = this.subscription.plan
        root.status = this.subscription.status
        root.term = this.subscription.term
        root = root.format_json().string()
        

output:
  http_client:
      url: "http://${STORAGE_SVC_ENDPOINT:localhost:8000}/subscription/"
      verb: POST
      headers:
        Content-Type: application/json
